global using System.Linq.Expressions;
global using AutoMapper;
global using FluentValidation;
global using FluentValidation.Results;
global using FurEverCarePlatform.Application.Commons;
global using FurEverCarePlatform.Application.Contracts;
global using FurEverCarePlatform.Application.Exception;
global using FurEverCarePlatform.Domain.Entities;
global using MediatR;
