name: Deploy ASP.NET Core to VPS

on:
  push:
    branches:
      - deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: run vps
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 8686
          script: |
            cd app/FurEverCarePlatform/
            git pull origin deploy  
            cd ..
            docker compose up -d petapi --build
